CREATE TABLE user (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(255),
password VARCHAR(255),
email VARCHAR(255),
date_ins TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE todo (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT,
description VARCHAR(255),
status VARCHAR(255) DEFAULT 'TODO',
date_ins TIMESTAMP DEFAULT CURRENT_TIMESTAMP);